### ISSUE TITLE
Broken Ray Movement Logic - Horizontal and Vertical Phasing

### ISSUE THREAD

**Issue by Metalsofa** [Metalsofa/Fourier#1]
Rays are now bouncing off of walls at almost all angles perfectly (at least as far as I can tell), but there is one issue with detecting collisions that is isolated to cases where the indecent ray is travelling either perfectly horizontally or perfectly vertically (it's possible that this issue is also happening with horizontal/vertical walls, but I haven't checked).
The logic for detecting a collision is really just the logic for detecting if the front segment of the ray is intersecting with the segment that constitutes a given wall (wall::body).  The function "intersection" in geometry.h is working properly, but the function "isintersect", which calls "intersection" and then detects whether the intersection lies on both of the argument segments, is broken. It's current method relies on checking if the intersection point is between the x and y boundaries for each segment--if so, return true, otherwise, return false--but in horizontal and vertical cases, where, say, the upper and lower boundaries are the same for one of the segments, nothing can lie between those boundaries and FALSE is automatically returned.

**Comment by dpakalarry** [comment]
Same cause as teleporting rays issue, fixed.
